# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/SBFILTER_II_0331/zed_filter_1.xdc

# Block Designs: bd/zynq_system/zynq_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system || ORIG_REF_NAME==zynq_system}]

# IP: bd/zynq_system/ip/zynq_system_processing_system7_0_0/zynq_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_0}]

# IP: bd/zynq_system/ip/zynq_system_hdmitx_iic_U_0/zynq_system_hdmitx_iic_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_hdmitx_iic_U_0 || ORIG_REF_NAME==zynq_system_hdmitx_iic_U_0}]

# IP: bd/zynq_system/ip/zynq_system_processing_system7_0_axi_periph_0/zynq_system_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_axi_periph_0}]

# IP: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_100M_0/zynq_system_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_100M_0}]

# IP: bd/zynq_system/ip/zynq_system_hdmitx_clkgen_U_0/zynq_system_hdmitx_clkgen_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_hdmitx_clkgen_U_0 || ORIG_REF_NAME==zynq_system_hdmitx_clkgen_U_0}]

# IP: bd/zynq_system/ip/zynq_system_xbar_0/zynq_system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_xbar_0 || ORIG_REF_NAME==zynq_system_xbar_0}]

# IP: bd/zynq_system/ip/zynq_system_hdmitx_U_0/zynq_system_hdmitx_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_hdmitx_U_0 || ORIG_REF_NAME==zynq_system_hdmitx_U_0}]

# IP: bd/zynq_system/ip/zynq_system_hdmitx_vdma_U_0/zynq_system_hdmitx_vdma_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_hdmitx_vdma_U_0 || ORIG_REF_NAME==zynq_system_hdmitx_vdma_U_0}]

# IP: bd/zynq_system/ip/zynq_system_axi_mem_intercon_0/zynq_system_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_axi_mem_intercon_0 || ORIG_REF_NAME==zynq_system_axi_mem_intercon_0}]

# IP: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_142M_0/zynq_system_rst_processing_system7_0_142M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_142M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_142M_0}]

# IP: bd/zynq_system/ip/zynq_system_filter_top_U_0/zynq_system_filter_top_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_filter_top_U_0 || ORIG_REF_NAME==zynq_system_filter_top_U_0}]

# IP: bd/zynq_system/ip/zynq_system_filter_vdma_U_0/zynq_system_filter_vdma_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_filter_vdma_U_0 || ORIG_REF_NAME==zynq_system_filter_vdma_U_0}]

# IP: bd/zynq_system/ip/zynq_system_axi_mem_intercon_1_0/zynq_system_axi_mem_intercon_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_axi_mem_intercon_1_0 || ORIG_REF_NAME==zynq_system_axi_mem_intercon_1_0}]

# IP: bd/zynq_system/ip/zynq_system_xbar_1/zynq_system_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_xbar_1 || ORIG_REF_NAME==zynq_system_xbar_1}]

# IP: bd/zynq_system/ip/zynq_system_const_vcc_U_0/zynq_system_const_vcc_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_const_vcc_U_0 || ORIG_REF_NAME==zynq_system_const_vcc_U_0}]

# IP: bd/zynq_system/ip/zynq_system_const_gnd_U_0/zynq_system_const_gnd_U_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_const_gnd_U_0 || ORIG_REF_NAME==zynq_system_const_gnd_U_0}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_0/zynq_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_0 || ORIG_REF_NAME==zynq_system_auto_pc_0}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_1/zynq_system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_1 || ORIG_REF_NAME==zynq_system_auto_pc_1}]

# IP: bd/zynq_system/ip/zynq_system_auto_pc_2/zynq_system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_auto_pc_2 || ORIG_REF_NAME==zynq_system_auto_pc_2}]

# XDC: bd/zynq_system/ip/zynq_system_processing_system7_0_0/zynq_system_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_processing_system7_0_0 || ORIG_REF_NAME==zynq_system_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/zynq_system/ip/zynq_system_hdmitx_iic_U_0/zynq_system_hdmitx_iic_U_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_hdmitx_iic_U_0 || ORIG_REF_NAME==zynq_system_hdmitx_iic_U_0}]

# XDC: bd/zynq_system/ip/zynq_system_hdmitx_iic_U_0/zynq_system_hdmitx_iic_U_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_100M_0/zynq_system_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_100M_0/zynq_system_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_100M_0}]

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_100M_0/zynq_system_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_xbar_0/zynq_system_xbar_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_hdmitx_vdma_U_0/zynq_system_hdmitx_vdma_U_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_hdmitx_vdma_U_0 || ORIG_REF_NAME==zynq_system_hdmitx_vdma_U_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_system/ip/zynq_system_hdmitx_vdma_U_0/zynq_system_hdmitx_vdma_U_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_hdmitx_vdma_U_0 || ORIG_REF_NAME==zynq_system_hdmitx_vdma_U_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_system/ip/zynq_system_hdmitx_vdma_U_0/zynq_system_hdmitx_vdma_U_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_142M_0/zynq_system_rst_processing_system7_0_142M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_142M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_142M_0}]

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_142M_0/zynq_system_rst_processing_system7_0_142M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_system_rst_processing_system7_0_142M_0 || ORIG_REF_NAME==zynq_system_rst_processing_system7_0_142M_0}]

# XDC: bd/zynq_system/ip/zynq_system_rst_processing_system7_0_142M_0/zynq_system_rst_processing_system7_0_142M_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_filter_vdma_U_0/zynq_system_filter_vdma_U_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_filter_vdma_U_0 || ORIG_REF_NAME==zynq_system_filter_vdma_U_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_system/ip/zynq_system_filter_vdma_U_0/zynq_system_filter_vdma_U_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_system_filter_vdma_U_0 || ORIG_REF_NAME==zynq_system_filter_vdma_U_0}] {/U0 }]/U0 ]]

# XDC: bd/zynq_system/ip/zynq_system_filter_vdma_U_0/zynq_system_filter_vdma_U_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_xbar_1/zynq_system_xbar_1_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_auto_pc_0/zynq_system_auto_pc_0_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_auto_pc_1/zynq_system_auto_pc_1_ooc.xdc

# XDC: bd/zynq_system/ip/zynq_system_auto_pc_2/zynq_system_auto_pc_2_ooc.xdc

# XDC: bd/zynq_system/zynq_system_ooc.xdc
